[tool.poetry]
name = "contacts"
version = "0.1.0"
description = "Contacts app"
authors = ["Alex Kydanov <a.kidanov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
asyncpg = "^0.27.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
